### ISSUE TITLE
The Model is not guaranteed to persist during app lifetime

### ISSUE THREAD

**Issue by dirk68-work** [mattgallagher/CwlFeedReader#1]
Him

great article. But I think there is a possible error. You create the model object in the app struct inside it's "description":

```Swift
WindowGroup {
    ContentView(model: Model())
}
```

Like with View code I think it is not guaranteed, that the model is not recreated sometime during the app's lifetime.
Better would probably be:

```Swift
@main
struct CwlFeedReaderApp: App {
        @StateObject model = Model()
	var body: some Scene {
		WindowGroup {
			ContentView(model: model)
		}
	}
}
```

**Comment by mattgallagher** [comment]
Hi @dirk68-fu, you raise an interesting complication and you're right, the way I've written things is not ideal (even though it happens to work).

I was going to say that your approach presents its own set of concerns – since changing any `@Published` property of the `model` will cause the entire `App.body` to regenerate – but I realize that Apple suggest exactly the approach you suggest [in the documentation for `App`](https://developer.apple.com/documentation/swiftui/app) so I guess you're correct and any regeneration concerns that I had should be mitigated in other ways.

Changes included in commit cd4fc85a043726e111b3b8a82eb153da75f1977e.
